### ISSUE TITLE
KeyError: 'train_subset'

### ISSUE THREAD

**Issue by hkunzhe** [HanxunH/Unlearnable-Examples#4]
Hi, thanks for sharing your codes!
I was able to run `perturbation.py` and `main.py` in the __Sample-wise noise for unlearnable example on CIFAR-10__ section. However, when I try to run `perturbation.py` in the __Class-wise noise for unlearnable example on CIFAR-10__ section, it raises the following error:
```
Traceback (most recent call last):
  File "perturbation.py", line 483, in <module>
    main()
  File "perturbation.py", line 469, in main
    noise = universal_perturbation(noise_generator, trainer, evaluator, model, criterion, optimizer, scheduler, random_noise, ENV)
  File "perturbation.py", line 191, in universal_perturbation
    for i, (images, labels) in tqdm(enumerate(data_loader[args.universal_train_target]), total=len(data_loader[args.universal_train_target])):
KeyError: 'train_subset'
```
Thus, I add an option `--universal_train_target train_dataset` to fix this error. Is this right to get the class-wise perturbation?
BTW, there are two typos (`--perturb_type samplewse`=>`--perturb_type samplewise`) in README.md.

**Comment by HanxunH** [comment]
Hi,

Thanks for your interest in our work. 

- Yes, `--universal_train_target train_dataset` should be added to the options for `classwise` setting. The README is missing it. In case of other errors, for each corresponding experiment in the paper, there is `exp_setting.sh` documents all the options.
- Thanks for the typos.
- I have updated the README for the  `--universal_train_target train_dataset` option as well as fixed the typos.

Best,

**Comment by hkunzhe** [comment]
Thanks for your quick reply!
It seems you have added the `--universal_train_target train_subset` rather than `--universal_train_target train_dataset` in README.md.

**Comment by HanxunH** [comment]
Sorry for the confusion.

I have double checked this. For `classwise`, as stated in the paper, we use `We use 20% of the training dataset.`, so this should indeed be `tran_subset`. To avoid the error, please use `--use_subset` in `perturbation.py`

Technically, it is also ok to use entire dataset to generate the noise. We use 20% to simulates that it can generalize to unseen data (the rest of 80%).

**Comment by hkunzhe** [comment]
Thanks for your clarification!
