### ISSUE TITLE
A problem with bi-level optimization in the article

### ISSUE THREAD

**Issue by butybone** [HanxunH/Unlearnable-Examples#9]
In the article, the author says "In order to find effective noise delta and unlearnable examples, the optimization steps for theta should be
limited, compared to standard or adversarial training ". 
1. What is the meaning of using bi-level optimization? In traditional adversarial attack, most works are focusing on optimized on data  but not  on model. 
2. Why the limit on optimization step on model can help finding effective noises as in the article?

I'm a new one studying on adversarial examples and I'm very interested in your brillant work, so my questions may sounds 'silly', but I'm really looking forward for your reply ! Thanks !

Here's my email morphling0223@foxmail.com

**Comment by HanxunH** [comment]
Hi,

Thanks for your interest in our work.

1. Compared to adversarial attacks, which generate the perturbation in the input space while the model is fixed. For the adversarial training, first, generate the perturbed input and then train on it. For the objective to find the noise we used in the paper, the formulation used is similar to adversarial training. Adversarial training uses maximizations in the inner optimization, while ours uses minimization. Outer optimizations are the same, minimize the classification loss and update the model's weight.
2. Because both terms are optimized towards the same objective, if the model's optimized weight can minimize the objective, there is no need for the unlearnable noise to minimize the objective. The unlearnable noise should play a major role in optimizing this objective, so it should limit on optimization step on the model. The model is kind of like guidance for generating the noise. 

Feels free to let me know if you have any other questions.

**Comment by butybone** [comment]
>

**Comment by butybone** [comment]
sorry to bother you again, XD
I have been running your code to test the effect of adversarial examples. However  I got an unexpected result when I was changing the parameter 'num_step' in the min_max_attack part. 
I think this parameter should control the total number of iterations of gradient based adversarial noise searching process, and a larger 'num_step' should stands for better optimization which leads to more effective adversarial attack.
However, after I increased 'num_step', I got a more accurate eval_acc, meaning the adversarial attack was failed.
So, did you ever get the results just like mine? or is it because I misunderstand the code?

**Comment by butybone** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
> 1. Compared to adversarial attacks, which generate the perturbation in the input space while the model is fixed. For the adversarial training, first, generate the perturbed input and then train on it. For the objective to find the noise we used in the paper, the formulation used is similar to adversarial training. Adversarial training uses maximizations in the inner optimization, while ours uses minimization. Outer optimizations are the same, minimize the classification loss and update the model's weight.
> 2. Because both terms are optimized towards the same objective, if the model's optimized weight can minimize the objective, there is no need for the unlearnable noise to minimize the objective. The unlearnable noise should play a major role in optimizing this objective, so it should limit on optimization step on the model. The model is kind of like guidance for generating the noise.
> 
> Feels free to let me know if you have any other questions.

sorry to bother you again, XD
I have been running your code to test the effect of adversarial examples. However I got an unexpected result when I was changing the parameter 'num_step' in the min_max_attack part.
I think this parameter should control the total number of iterations of gradient based adversarial noise searching process, and a larger 'num_step' should stands for better optimization which leads to more effective adversarial attack.
However, after I increased 'num_step', I got a more accurate eval_acc, meaning the adversarial attack was failed.
So, did you ever get the results just like mine? or is it because I misunderstand the code?

**Comment by HanxunH** [comment]
Hi,

Yes, the num_steps is the total amount of perturbation steps. Larger steps should usually be better. Better adjust the step_size as well.

Can you provide some details on how you get the eval_acc? Is it poisoning 100% of the dataset with min_max noise and training a model on this data, the eval_acc on clean set?

**Comment by butybone** [comment]
> 
perturbation setting:
export config_path=configs/cifar10
export dataset_type=CIFAR10
export poison_dataset_type=PoisonCIFAR10
export attack_type=min-max
export perturb_type=classwise
export base_version=resnet18
export epsilon=8
export step_size=0.8
export num_steps=1
export universal_stop_error=0.8
export universal_train_target='train_subset'

train setting:
python3 -u main.py    --version                 resnet18
                                   --train_data_type     PoisonCIFAR10
                                   --poison_rate            1.0
                                   --perturb_type         classwise
                                   --attack_type           min-max

In the 'universal_perturbation' function of 'perturbation.py' : during 'condition' iteration which is controled by 'universal_stop_error' parameter, first the codes search the min-max noise and then the noise is added to the clean dataset as a adversarial input to the model. Next, the model returns an acc using the 'universal_perturbation_eval' function.
   
![image](https://user-images.githubusercontent.com/37739252/156682885-42a887c3-144d-496a-b803-bc2347eb6b2c.png)


the resnet18 model trained on clean CIFAR10 can get an accuracy about 93%, below is the result of  acc output of the 'universal_perturbation_eval'.
I think the acc should decrease along with larger num_step.
num_step =1 
![image](https://user-images.githubusercontent.com/37739252/156683269-f1a3913c-1900-40fb-af90-c333771b35c7.png)

num_step = 30 (change nothing but num_step)
![image](https://user-images.githubusercontent.com/37739252/156682989-18c3a514-1273-4eda-a7ad-bb01f7e111bc.png)

**Comment by butybone** [comment]
Would you like to exchange contact details? If it's ok, you can send your Wechat ID to my email(morphling0223@foxmail.com), or leave your email. Thanks anyway!

**Comment by butybone** [comment]
> Hi,
> 
> Yes, the num_steps is the total amount of perturbation steps. Larger steps should usually be better. Better adjust the step_size as well.
> 
> Can you provide some details on how you get the eval_acc? Is it poisoning 100% of the dataset with min_max noise and training a model on this data, the eval_acc on clean set?

[](https://user-images.githubusercontent.com/37739252/156682885-42a887c3-144d-496a-b803-bc2347eb6b2c.png)[](https://user-images.githubusercontent.com/37739252/156683269-f1a3913c-1900-40fb-af90-c333771b35c7.png)perturbation setting:
export config_path=configs/cifar10
export dataset_type=CIFAR10
export poison_dataset_type=PoisonCIFAR10
export attack_type=min-max
export perturb_type=classwise
export base_version=resnet18
export epsilon=8
export step_size=0.8
export num_steps=1
export universal_stop_error=0.8
export universal_train_target='train_subset'

train setting:
python3 -u main.py --version resnet18
--train_data_type PoisonCIFAR10
--poison_rate 1.0
--perturb_type classwise
--attack_type min-max

In the 'universal_perturbation' function of 'perturbation.py' : during 'condition' iteration which is controled by 'universal_stop_error' parameter, first the codes search the min-max noise and then the noise is added to the clean dataset as a adversarial input to the model. Next, the model returns an acc using the 'universal_perturbation_eval' function.


![2](https://user-images.githubusercontent.com/37739252/156871527-1b07327b-00e5-4a95-a7a4-f69a7d021c91.png)


the resnet18 model trained on clean CIFAR10 can get an accuracy about 93%, below is the result of acc output of the 'universal_perturbation_eval'.
I think the acc should decrease along with larger num_step.
num_step =1
image
![3](https://user-images.githubusercontent.com/37739252/156871533-91c7a25c-46c5-41b1-9278-e39508564277.png)

num_step = 30 (change nothing but num_step)
![4](https://user-images.githubusercontent.com/37739252/156871542-e0ae9499-6c37-4e00-9dda-751aec23e8d8.png)

**Comment by butybone** [comment]
> Hi,
> 
> Yes, the num_steps is the total amount of perturbation steps. Larger steps should usually be better. Better adjust the step_size as well.
> 
> Can you provide some details on how you get the eval_acc? Is it poisoning 100% of the dataset with min_max noise and training a model on this data, the eval_acc on clean set?

Just found out that I made a mistake when choosing parameters, thanks.
